
# Records that caused errors
# ERROR:2022-04-19 07:04:22,766: /home/string1, line 86249: Bad record: Not enough fields to get value for ineligiblePendTime.
"JOB_FINISH" "9.13" 1554995290 513431 31875 33833011 4 1554995282 0 0 1554995282 "string2" "batch" "span[hosts=1]" "" "" "string3" "/string4/string2/string5" "" "/tmp/string6.stdout" "/tmp/string6.stderr" "1554995282.513431" 0 4 "string7" "string7" "string7" "string7" 64 10.1 "string7=1.31825673855641e-06" "./string8" 14.093857 1.747734 113252 0 -1 0 0 64357 5 0 1440 9736 -1 0 0 0 474235 202 -1 "" "default" 0 4 "" "" 0 61104 458608 "" "" "" "" 0 "" 0 "" -1 "/string2" "" "" "" -1 "" "" 80 "" 1554995282 "" "" 0 0 -1 64 61104 "select[ (type == any)] order[r15s:pg] span[hosts=1] " "" -1 "" -1 0 "" 0 0 "" 8 "/data/tmp" 0 "" 0.000000 0.00 0.00 0.00 0.00 4 "string7" "string7" "string7" "string7"

# ERROR:2022-04-19 07:04:22,766: /home/string1, line 86250: Bad record: Not enough fields to get value for ineligiblePendTime.
"JOB_FINISH" "9.13" 1554995292 513433 31875 33833011 4 1554995285 0 0 1554995287 "string2" "batch" "span[hosts=1]" "" "" "string3" "/string4/string2/string9" "" "/tmp/string10.stdout" "/tmp/string10.stderr" "1554995285.513433" 0 4 "string11" "string11" "string11" "string11" 64 10.1 "string7=1.38038426460288e-06" "./string8" 9.170605 1.230812 114388 0 -1 0 0 65679 5 0 1440 9736 -1 0 0 0 386780 176 -1 "" "default" 0 4 "" "" 0 101812 507220 "" "" "" "" 0 "" 0 "" -1 "/string2" "" "" "" -1 "" "" 80 "" 1554995287 "" "" 0 0 -1 64 101812 "select[ (type == any)] order[r15s:pg] span[hosts=1] " "" -1 "" -1 0 "" 0 0 "" 5 "/data/tmp" 0 "" 0.000000 0.00 0.00 0.00 0.00 4 "string11" "string11" "string11" "string11"
